name: Cancel
on:
  - push
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - uses: styfle/cancel-workflow-action@0.6.0
        with:
          workflow_id: cancel.yml, validate.yml
          access_token: ${{ github.token }}
