name: Validate - new-universe-demo
on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
      - assigned
      - labeled
      - review_requested
env:
  APP_NAME: new-universe-demo
  HOME: /actions-runner/_work
  GITHUB_ACCESS_TOKEN: ${{ secrets.CI_BOT_TOKEN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  AWS_DEFAULT_REGION: ap-south-1
  AWS_S3_STAGE_CACHE_BUCKET_NAME: rzp-1018-nonprod-actions-cache
  AWS_S3_STAGE_ROLE: arn:aws:iam::101860328116:role/gha-stage-new-universe-demo-action
jobs:
  validate:
    name: Validate
    if: github.event.action == 'opened' || github.event.action == 'synchronize' || github.event.action == 'reopened'
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Setup Node v14.19
        uses: actions/setup-node@v2
        with:
          node-version: "14.19"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1.8.15
        with:
          install-command: yarn --frozen-lockfile
      - name: Enable webpack persistent caching
        uses: actions/cache@v3
        id: build-webpack-persistent-cache
        with:
          path: node_modules/.cache/webpack
          key: build-${{ hashFiles('**/webpack.*.js') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |-
            build-${{ hashFiles('**/webpack.*.js') }}-${{ hashFiles('**/yarn.lock') }}
            build-${{ hashFiles('**/webpack.*.js') }}-
      - name: Lint Code
        run: yarn lint
      - name: Run Tests
        run: yarn test
      - name: Build Application
        run: yarn production:build
  danger-js:
    name: Run DangerJS
    runs-on: self-hosted
    timeout-minutes: 10
    steps:
      - name: Configure Stage AWS Credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ env.AWS_S3_STAGE_ROLE }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}
          role-duration-seconds: 900
      - name: Checkout Codebase
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.CI_BOT_TOKEN }}
      - name: Setup Node v14.19
        uses: actions/setup-node@v2
        with:
          node-version: "14.19"
      - name: Install Yarn
        run: npm install -g yarn
      - name: Setup Cache & Install Dependencies
        uses: bahmutov/npm-install@v1.8.15
        with:
          install-command: yarn --frozen-lockfile
      - name: Enable webpack persistent caching
        uses: actions/cache@v3
        id: build-webpack-persistent-cache
        with:
          path: node_modules/.cache/webpack
          key: build-${{ hashFiles('**/webpack.*.js') }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |-
            build-${{ hashFiles('**/webpack.*.js') }}-${{ hashFiles('**/yarn.lock') }}
            build-${{ hashFiles('**/webpack.*.js') }}-
      - name: Install chrome dependencies
        run: >-
          apt-get -y install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1
          libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6
          libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - name: Install Latest Chrome
        uses: browser-actions/setup-chrome@latest
      - name: Set Chrome Path
        id: set-chrome-path
        run: echo "::set-output name=CHROME_EXECUTABLE_PATH::$(which chrome)"
      - name: Danger JS
        run: yarn danger ci
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DANGER_DISABLE_TRANSPILATION: "true"
          STAGE: beta
          CHROME_EXECUTABLE_PATH: ${{ steps.set-chrome-path.outputs.CHROME_EXECUTABLE_PATH }}
